---
- name: Update and Upgrade APT packages without dist-upgrade
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Optional: cache is considered valid for 1 hour

    - name: Upgrade APT packages (without dist-upgrade)
      apt:
        upgrade: safe

        upgrade: dist
